name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Check if track dependencies are up to date
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579

      - name: Check if track dependencies are up to date
        run: cd track_deps_are_up_to_date && cargo test
